### ISSUE TITLE
Functions to calculate between Geo- and GPU coordinates

### ISSUE THREAD

**Issue by DerKarlos** [DerKarlos/OSMeta#51]
If and as we now use an Earth sphere, we can't just use the GPU coordinates or the camera Transform to for orientation relative to the map.
For our development and for future users we should add some helper functions.

Examples:
* The camera speed should depend on the height above the ground (the Earth-Sphere surface). How to get the height?
* A tile should be loaded first if it is in the same direction as the camera (player) looks. How to get the direction?
* A new "thing" should be added at a lat/lon/elevate place on the map. How to get the GPU Transform?

We may have functions like
camera.get_local_transform / .get_earth_rotation / .get_map_position    (names to be discussed)
The position in meter relativ to the start position of the scene or the center of the first loaded tile.
(Terrain rendering is to be considered if implemented)
The functions may get added to our existing "classes" like GeoPos.

**Comment by oli-obk** [comment]
> The camera speed should depend on the height above the ground (the Earth-Sphere surface). How to get the height?

a bevy system for changing the speed depending on the height:

```rust
fn update_camera_speed(
    mut movement_settings: ResMut<MovementSettings>,
    fly_cam: Query<&Transform, (With<FlyCam>, Without<TileMap>)>,
    tilemap: Query<&Transform, (With<TileMap>, Without<FlyCam>)>,
) {
    movement_settings.speed =
        3.5 * (fly_cam.single().translation.distance(tilemap.single().translation) - EARTH_RADIUS) + 100.0
}
```

You can change the `3.5` to change how much the height affects the speed (or even switch to something entirely different like an exponential formula


> A tile should be loaded first if it is in the same direction as the camera (player) looks. How to get the direction?

in `load_next_tile` you can use `flycam_pos.single().forward()` to get a vector in the direction the camera is looking.

> A new "thing" should be added at a lat/lon/elevate place on the map. How to get the GPU Transform?

`GeoPos { lat: 49.0, lon: 9.0 }.to_cartesian()` gives you the coordinates on the surface of the earth. We can change `to_cartesian` to accept any elevation.

In order for the thing to actually show up in the right place, it needs to be made a child of the `TileMap`. I will fix this soon, so that we can just use global world coordinates by making the earth sphere be centered at 0,0,0
